"""feat: Sync all models with database."""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '324bfa59320b'
down_revision: Union[str, None] = 'aaf8a57829ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
