"""feat: add celery models and notifications structure.

Revision ID: 4fa22945fdee
Revises: 0384266657a9
Create Date: 2025-12-26 19:05:05.042456

"""

# ruff: noqa: D400, D415, D103, E501, D105
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4fa22945fdee'
down_revision: Union[str, None] = '0384266657a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'media',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('file_path', sa.String(length=512), nullable=False),
        sa.Column('mime_type', sa.String(length=50), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_path'),
    )
    op.create_index('ix_media_active', 'media', ['active'], unique=False)
    op.create_index(
        'ix_media_created_at', 'media', ['created_at'], unique=False
    )
    op.create_index('ix_media_file_path', 'media', ['file_path'], unique=False)
    op.create_foreign_key(None, 'cafe_managers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cafe_managers', 'cafes', ['cafe_id'], ['id'])
    op.drop_column('cafe_managers', 'id')
    op.add_column('cafes', sa.Column('photo_id', sa.UUID(), nullable=True))
    op.alter_column(
        'cafes',
        'name',
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        'cafes',
        'address',
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, 'cafes', 'media', ['photo_id'], ['id'], ondelete='SET NULL'
    )
    op.drop_column('cafes', 'closing_time')
    op.drop_column('cafes', 'logo_id')
    op.drop_column('cafes', 'opening_time')
    op.drop_column('cafes', 'city')
    op.drop_column('cafes', 'email')
    op.drop_column('cafes', 'latitude')
    op.drop_column('cafes', 'longitude')
    op.drop_column('cafes', 'average_bill')
    op.add_column('tables', sa.Column('seats', sa.Integer(), nullable=False))
    op.alter_column(
        'tables',
        'description',
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    op.drop_index('idx_table_active', table_name='tables')
    op.drop_index('idx_table_cafe_id', table_name='tables')
    op.drop_constraint(
        'tables_cafe_id_table_number_key', 'tables', type_='unique'
    )
    op.create_index('ix_tables_id', 'tables', ['id'], unique=False)
    op.drop_constraint('tables_cafe_id_fkey', 'tables', type_='foreignkey')
    op.create_foreign_key(
        None, 'tables', 'cafes', ['cafe_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_column('tables', 'has_power_outlet')
    op.drop_column('tables', 'seat_count')
    op.drop_column('tables', 'is_smoking_area')
    op.drop_column('tables', 'has_window')
    op.drop_column('tables', 'table_number')
    op.alter_column(
        'users',
        'username',
        existing_type=sa.VARCHAR(),
        comment='Имя пользователя от 3 до 50 символов',
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'phone',
        existing_type=sa.VARCHAR(),
        comment='Номер телефона от 10 до 20 символов',
        existing_nullable=True,
    )
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column(
        'users',
        'phone',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='Номер телефона от 10 до 20 символов',
        existing_nullable=True,
    )
    op.alter_column(
        'users',
        'username',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='Имя пользователя от 3 до 50 символов',
        existing_nullable=False,
    )
    op.add_column(
        'tables',
        sa.Column(
            'table_number', sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'tables',
        sa.Column(
            'has_window',
            sa.BOOLEAN(),
            server_default=sa.text('false'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'tables',
        sa.Column(
            'is_smoking_area',
            sa.BOOLEAN(),
            server_default=sa.text('false'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'tables',
        sa.Column(
            'seat_count', sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'tables',
        sa.Column(
            'has_power_outlet',
            sa.BOOLEAN(),
            server_default=sa.text('false'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.create_foreign_key(
        'tables_cafe_id_fkey', 'tables', 'cafes', ['cafe_id'], ['id']
    )
    op.drop_index('ix_tables_id', table_name='tables')
    op.create_unique_constraint(
        'tables_cafe_id_table_number_key',
        'tables',
        ['cafe_id', 'table_number'],
    )
    op.create_index('idx_table_cafe_id', 'tables', ['cafe_id'], unique=False)
    op.create_index('idx_table_active', 'tables', ['active'], unique=False)
    op.alter_column(
        'tables',
        'description',
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.drop_column('tables', 'seats')
    op.add_column(
        'cafes',
        sa.Column(
            'average_bill',
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'cafes',
        sa.Column(
            'longitude',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'cafes',
        sa.Column(
            'latitude',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'cafes',
        sa.Column(
            'email', sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        'cafes',
        sa.Column(
            'city', sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'cafes',
        sa.Column(
            'opening_time',
            postgresql.TIME(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'cafes',
        sa.Column(
            'logo_id',
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'cafes',
        sa.Column(
            'closing_time',
            postgresql.TIME(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, 'cafes', type_='foreignkey')
    op.alter_column(
        'cafes',
        'address',
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        'cafes',
        'name',
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column('cafes', 'photo_id')
    op.add_column(
        'cafe_managers',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(None, 'cafe_managers', type_='foreignkey')
    op.drop_constraint(None, 'cafe_managers', type_='foreignkey')
    op.drop_index('ix_media_file_path', table_name='media')
    op.drop_index('ix_media_created_at', table_name='media')
    op.drop_index('ix_media_active', table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
