"""add action_cafes and dish_cafes

Revision ID: 6b1e896aa91b
Revises: f5f10f45425e
Create Date: 2026-01-12 00:34:43.722576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1e896aa91b'
down_revision: Union[str, None] = 'f5f10f45425e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
