"""Update models after refactoring.

Revision ID: aaf8a57829ce
Revises: e578c4e9a8c5
Create Date: 2025-12-28 08:21:32.555134

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aaf8a57829ce'
down_revision: Union[str, None] = 'e578c4e9a8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run the upgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('photo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, 'cafes', 'media', ['photo_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Run the downgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cafes', type_='foreignkey')
    op.drop_column('cafes', 'photo_id')
    # ### end Alembic commands ###
