"""Add booking models and relationships

Revision ID: e578c4e9a8c5
Revises: 4fa22945fdee
Create Date: 2025-12-27 21:50:17.821366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e578c4e9a8c5'
down_revision: Union[str, None] = '4fa22945fdee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('guest_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_cafe', 'bookings', ['cafe_id'], unique=False)
    op.create_index('ix_booking_date', 'bookings', ['booking_date'], unique=False)
    op.create_index('ix_booking_user', 'bookings', ['user_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_cafe_id'), 'slots', ['cafe_id'], unique=False)
    op.create_table('table_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_slot_booking', 'table_slots', ['booking_id'], unique=False)
    op.create_index('ix_table_slot_table_slot', 'table_slots', ['table_id', 'slot_id'], unique=False)
    op.drop_constraint('cafes_photo_id_fkey', 'cafes', type_='foreignkey')
    op.drop_column('cafes', 'photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('photo_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('cafes_photo_id_fkey', 'cafes', 'media', ['photo_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_table_slot_table_slot', table_name='table_slots')
    op.drop_index('ix_table_slot_booking', table_name='table_slots')
    op.drop_table('table_slots')
    op.drop_index(op.f('ix_slots_cafe_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index('ix_booking_user', table_name='bookings')
    op.drop_index('ix_booking_date', table_name='bookings')
    op.drop_index('ix_booking_cafe', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
