"""add action_cafes and dish_cafes

Revision ID: f5f10f45425e
Revises: 4650ccdd790e
Create Date: 2026-01-11 23:59:40.274000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f10f45425e'
down_revision: Union[str, None] = '4650ccdd790e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_cafes',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('action_id', 'cafe_id')
    )
    op.create_table('dish_cafes',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'cafe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish_cafes')
    op.drop_table('action_cafes')
    # ### end Alembic commands ###
