"""Add booking table

Revision ID: 0b3135541aa1
Revises: 4a1d4ec77033
Create Date: 2025-12-18 17:45:28.445720

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b3135541aa1'
down_revision: Union[str, None] = '4a1d4ec77033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cafes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'slots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'tables',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_date', sa.DateTime(), nullable=False),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('note', sa.String(length=256), nullable=True),
        sa.Column('guest_number', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_booking_cafe', 'bookings', ['cafe_id'], unique=False)
    op.create_index(
        'ix_booking_date', 'bookings', ['booking_date'], unique=False
    )
    op.create_index('ix_booking_user', 'bookings', ['user_id'], unique=False)
    op.create_table(
        'table_slots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('table_id', sa.Integer(), nullable=False),
        sa.Column('slot_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['booking_id'], ['bookings.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['slot_id'], ['slots.id']),
        sa.ForeignKeyConstraint(['table_id'], ['tables.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('table_id', 'slot_id', name='uq_table_slot'),
    )
    op.create_index(
        'ix_table_slot_booking', 'table_slots', ['booking_id'], unique=False
    )
    op.create_index(
        'ix_table_slot_table_slot',
        'table_slots',
        ['table_id', 'slot_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_table_slot_table_slot', table_name='table_slots')
    op.drop_index('ix_table_slot_booking', table_name='table_slots')
    op.drop_table('table_slots')
    op.drop_index('ix_booking_user', table_name='bookings')
    op.drop_index('ix_booking_date', table_name='bookings')
    op.drop_index('ix_booking_cafe', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('tables')
    op.drop_table('slots')
    op.drop_table('cafes')
    # ### end Alembic commands ###
