"""Add cafe_manager relationship

Revision ID: c0fe578d5b93
Revises: 28b434f0a9c8
Create Date: 2025-12-19 01:10:01.668320

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c0fe578d5b93'
down_revision: Union[str, None] = '28b434f0a9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
