"""Fix booking status column type from Integer to String.

Revision ID: 9a1b49f6a431
Revises: 9a1b49f6a430
Create Date: 2026-01-08 17:30:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a1b49f6a431'
down_revision: Union[str, None] = '9a1b49f6a430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade: Change booking status column type Integer to String.

    This migration modifies the bookings table to use VARCHAR type for the
    status column instead of INTEGER, allowing proper storage of enum string
    values ('pending', 'confirmed', 'cancelled', 'completed').
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'status',
               existing_type=sa.Integer(),
               type_=sa.String(),
               existing_nullable=False,
               existing_default='pending')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade: Revert booking status column type String to Integer.

    This migration reverts the column type back to INTEGER in case the
    migration needs to be rolled back. Note: this may cause data loss if
    status values were already stored as strings.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'status',
               existing_type=sa.String(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_default='pending')
    # ### end Alembic commands ###
