"""Add cafe_manager table

Revision ID: 28b434f0a9c8
Revises: 0b3135541aa1
Create Date: 2025-12-19 01:00:56.433088

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '28b434f0a9c8'
down_revision: Union[str, None] = '0b3135541aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cafe_managers',
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('cafe_id', 'user_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe_managers')
    # ### end Alembic commands ###
